# This is a basic workflow to help you get started with Actions

name: Dione Maven Build CI for Pull request to main branch


# Controls when the workflow will run
on:
  # Triggers the workflow on every pull request
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@v2

      - name: Setup Java env
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '8'
          distribution: 'zulu'
          check-latest: true

      - name: Maven build
        run:
            mvn -B -V clean package

      - name: Upload jar file
        uses: actions/upload-artifact@v2
        with:
          name: dione-spark-target
          path: |
            dione-hadoop/target/*.jar
            dione-spark/target/*.jar
            dione-spark/src/test/python

  python-api-tests:
    needs: build_jar
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [ '3.6' ]

    steps:
      - name: Download the artifacts
        uses: actions/download-artifact@v2
        with:
          name: dione-spark-target

      - name: Setup Java env
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '8'
          distribution: 'zulu'
          check-latest: true

      - name: setup Python env
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: run Python API tests
        run: |
          find .
          export PYTHONPATH=`echo dione-spark/target/dione-spark-*-SNAPSHOT.jar`
          python -V
          pip install pypandoc==1.7.5
          pip install pytest pyspark==3.3.0
          pytest -v
